export const formatPlanPrice = (amount: number) => {
  const rounded = Math.round(amount * 100) / 100;
  return Number.isInteger(rounded) ? String(rounded) : rounded.toFixed(2);
};

export const parseExtraAmount = (value: unknown): number => {
  const parsed = parseFloat(String(value ?? '').replace(/[^0-9.-]/g, ''));
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 0;
};

export const parsePlanPrice = (value: unknown): number => {
  const parsed = parseFloat(String(value ?? '').replace(/[^0-9.-]/g, ''));
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : 0;
};

export const cleanFeatureText = (feature: unknown): string => {
  let text = String(feature ?? '')
    .replace(/\\"/g, '"')
    .replace(/^''+/g, '')
    .replace(/^[\s"'`]+|[\s"'`,]+$/g, '')
    .trim();

  text = text.replace(/,\s*$/g, '').replace(/^["']+|["']+$/g, '').trim();

  if (!text || text === "''" || text === '"' || text === '""') return '';
  if (/^["'`]+$/.test(text)) return '';
  return text;
};

const extractFeatureEntry = (item: unknown): string => {
  if (item == null) return '';

  if (typeof item === 'object' && !Array.isArray(item)) {
    const obj = item as Record<string, unknown>;
    return cleanFeatureText(
      obj.text ??
        obj.title ??
        obj.name ??
        obj.label ??
        obj.description ??
        obj.feature ??
        obj.value,
    );
  }

  return cleanFeatureText(item);
};

export const normalizePlanFeatures = (features: unknown): string[] => {
  if (features == null) return [];

  if (typeof features === 'string') {
    const trimmed = features.trim();
    if (!trimmed) return [];

    if (trimmed.startsWith('[') || trimmed.startsWith('{')) {
      try {
        return normalizePlanFeatures(JSON.parse(trimmed));
      } catch {
        // fall through
      }
    }

    if (trimmed.includes('\n')) {
      return normalizePlanFeatures(trimmed.split('\n'));
    }

    if (trimmed.includes(',')) {
      return normalizePlanFeatures(trimmed.split(','));
    }

    const single = cleanFeatureText(trimmed);
    return single ? [single] : [];
  }

  if (!Array.isArray(features)) return [];

  const out: string[] = [];

  for (const item of features) {
    if (typeof item === 'object' && item !== null && !Array.isArray(item)) {
      const text = extractFeatureEntry(item);
      if (text) out.push(text);
      continue;
    }

    const raw = String(item ?? '');
    if (!raw.trim()) continue;

    const chunks = raw.includes('","')
      ? raw.split(/"\s*,\s*"/)
      : raw.includes('", "')
        ? raw.split(/",\s*"/)
        : [raw];

    for (const chunk of chunks) {
      const cleaned = cleanFeatureText(chunk);
      if (cleaned) out.push(cleaned);
    }
  }

  return [...new Set(out)];
};

const AUTO_GENERATED_FEATURE_PATTERNS = [
  /^chat frequency\s*:/i,
  /^video meetings\s*:/i,
  /^symptom tracking included$/i,
];

const isAutoGeneratedFeature = (text: string) =>
  AUTO_GENERATED_FEATURE_PATTERNS.some((pattern) => pattern.test(text.trim()));

export const getPlanFeatures = (plan: Record<string, unknown> | null | undefined): string[] => {
  if (!plan) return [];

  return normalizePlanFeatures(plan.features).filter(
    (feature) => !isAutoGeneratedFeature(feature),
  );
};

const PLAN_ICON_MAP: Record<string, string> = {
  shield: "shield-check-outline",
  star: "star-circle-outline",
  badge: "medal-outline",
  crown: "crown-outline",
  diamond: "diamond-stone",
  "military-tech": "medal-outline",
  premium: "star-circle-outline",
  pro: "certificate-outline",
  elite: "crown-outline",
};

export const getPlanIconName = (icon?: string) => {
  const trimmed = icon?.trim();
  if (!trimmed) return "clipboard-pulse-outline";

  const mapped = PLAN_ICON_MAP[trimmed.toLowerCase()];
  return mapped ?? trimmed;
};

export const getPlanExtraAmount = (plan: Record<string, unknown> | null | undefined): number => {
  if (!plan) return 0;

  const candidates = [
    plan.extraAmount,
    plan.extra_amount,
    plan.consultationAmount,
    plan.consultationPrice,
    plan.addonAmount,
  ];

  for (const value of candidates) {
    const parsed = parseExtraAmount(value);
    if (parsed > 0) return parsed;
  }

  return 0;
};

export const getPlanExtraAmountText = (
  plan: Record<string, unknown> | null | undefined,
): string | undefined => {
  if (!plan) return undefined;

  const text =
    plan.extraAmountT ??
    plan.extra_amount_t ??
    plan.extraAmountText ??
    plan.extraDescription ??
    plan.extraTitle;

  return typeof text === 'string' && text.trim() ? text.trim() : undefined;
};

export const getPlanExtraBenefits = (
  plan: Record<string, unknown> | null | undefined,
): string[] => {
  if (!plan) return [];

  const sources = [plan.extraBenefits, plan.extra_benefits, plan.extraBenefitList];
  const merged: string[] = [];

  for (const source of sources) {
    merged.push(...normalizePlanFeatures(source));
  }

  return [...new Set(merged)];
};

export const getPlanExtraAddonBenefits = (
  plan: Record<string, unknown> | null | undefined,
): string[] => {
  if (!plan) return [];

  const candidates = [
    plan.extraAddonBenefits,
    plan.extraAmountBenefits,
    plan.extraIncludes,
    plan.extraFeatures,
    plan.extra_benefits,
  ];

  for (const value of candidates) {
    const items = normalizePlanFeatures(value);
    if (items.length > 0) return items;
  }

  return [];
};

export const hasPlanOptionalExtra = (
  plan: Record<string, unknown> | null | undefined,
): boolean => getPlanExtraAmount(plan) > 0;

export const unwrapSubscriptionPlans = (payload: unknown): unknown[] => {
  if (Array.isArray(payload)) return payload;
  if (!payload || typeof payload !== 'object') return [];

  const record = payload as Record<string, unknown>;
  if (Array.isArray(record.data)) return record.data;
  if (Array.isArray(record.subscriptions)) return record.subscriptions;
  if (Array.isArray(record.plans)) return record.plans;

  return [];
};

export const normalizeSubscriptionPlan = (raw: unknown) => {
  if (!raw || typeof raw !== 'object') return null;

  const plan = raw as Record<string, unknown>;
  const id = String(plan._id ?? plan.id ?? '');

  return {
    ...plan,
    _id: id,
    id: String(plan.id ?? plan._id ?? id),
    name: String(plan.name ?? plan.title ?? 'Plan').trim(),
    price: parsePlanPrice(plan.price),
    yearlyPrice: parsePlanPrice(plan.yearlyPrice),
    totalAmount: parsePlanPrice(plan.totalAmount),
    description: String(plan.description ?? plan.subtitle ?? '').trim(),
    period: String(plan.period ?? '/month'),
    savings: plan.savings != null ? String(plan.savings) : undefined,
    features: getPlanFeatures(plan),
    extraBenefits: getPlanExtraBenefits(plan),
    color: String(plan.color ?? '#3B82F6'),
    icon: String(plan.icon ?? 'shield'),
    popular: Boolean(plan.popular),
    paymentUrl: plan.paymentUrl ? String(plan.paymentUrl) : undefined,
    extraAmount: plan.extraAmount,
    extraAmountT: getPlanExtraAmountText(plan),
    isActive: plan.isActive !== false,
  };
};

export const normalizeSubscriptionPlans = (payload: unknown) =>
  unwrapSubscriptionPlans(payload)
    .map(normalizeSubscriptionPlan)
    .filter((plan): plan is NonNullable<typeof plan> => !!plan && plan.isActive !== false);
