import { StyleSheet, Dimensions } from 'react-native';
const { width: _width, height: _height } = Dimensions.get('window');

const styless = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#E8F5E8' },
  homeContent: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20 },
  title: { fontSize: 32, fontWeight: 'bold', color: '#2E7D32', marginBottom: 10, textAlign: 'center' },
  subtitle: { fontSize: 18, color: '#4CAF50', textAlign: 'center', marginBottom: 40, fontStyle: 'italic' },
  gameButtons: { width: '100%', marginBottom: 30 },
  gameButton: { backgroundColor: '#fff', borderRadius: 20, padding: 25, marginBottom: 20, alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 5 },
  breathingButton: { borderLeftWidth: 5, borderLeftColor: '#4CAF50' },
  tapButton: { borderLeftWidth: 5, borderLeftColor: '#FF9800' },
  gameButtonEmoji: { fontSize: 40, marginBottom: 10 },
  gameButtonText: { fontSize: 20, fontWeight: 'bold', color: '#2E7D32', marginBottom: 5 },
  gameButtonDesc: { fontSize: 14, color: '#666' },
  scoresButton: { backgroundColor: '#2196F3', borderRadius: 15, paddingVertical: 15, paddingHorizontal: 30 },
  scoresButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  gameContainer: { flex: 1, backgroundColor: '#E8F5E8' },
  gameHeader: { flexDirection: 'row', alignItems: 'center', padding: 20, backgroundColor: '#4CAF50' },
  backButton: { marginRight: 15 },
  backButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  gameTitle: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
  breathingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20 },
  breathingInstructions: { fontSize: 18, color: '#2E7D32', textAlign: 'center', marginBottom: 40, fontWeight: '500' },
  breathingCircleContainer: { alignItems: 'center', justifyContent: 'center', marginBottom: 40 },
  breathingCircle: { width: 200, height: 200, borderRadius: 100, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 10 },
  breathingText: { color: '#fff', fontSize: 24, fontWeight: 'bold' },
  cycleCounter: { fontSize: 20, color: '#2E7D32', fontWeight: 'bold', marginBottom: 30 },
  breathingControls: { alignItems: 'center' },
  startButton: { backgroundColor: '#4CAF50', borderRadius: 25, paddingVertical: 15, paddingHorizontal: 40 },
  startButtonText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  stopButton: { backgroundColor: '#f44336', borderRadius: 25, paddingVertical: 15, paddingHorizontal: 40 },
  stopButtonText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  tapGameStats: { flexDirection: 'row', justifyContent: 'space-around', backgroundColor: '#fff', paddingVertical: 15, marginHorizontal: 20, marginTop: 20, borderRadius: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  statText: { fontSize: 18, fontWeight: 'bold', color: '#2E7D32' },
  gameArea: { flex: 1, marginHorizontal: 20, marginTop: 20, position: 'relative' },
  face: { position: 'absolute', width: 60, height: 60, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff', borderRadius: 30, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 4, elevation: 5 },
  faceEmoji: { fontSize: 35 },
  gameControls: { alignItems: 'center', padding: 20 },
  gameOverContainer: { alignItems: 'center' },
  gameOverText: { fontSize: 24, fontWeight: 'bold', color: '#4CAF50', marginBottom: 10 },
  finalScoreText: { fontSize: 20, color: '#2E7D32', marginBottom: 20 },
  playAgainButton: { backgroundColor: '#FF9800', borderRadius: 25, paddingVertical: 15, paddingHorizontal: 30 },
  playAgainButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  instructions: { backgroundColor: '#fff', marginHorizontal: 20, marginBottom: 20, padding: 20, borderRadius: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  instructionText: { fontSize: 16, color: '#2E7D32', textAlign: 'center', lineHeight: 24 },
  scoresContainer: { flex: 1, padding: 20 },
  scoreSection: { backgroundColor: '#fff', borderRadius: 10, padding: 20, marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  scoreSectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#2E7D32', marginBottom: 15 },
  noScoresText: { fontSize: 16, color: '#666', fontStyle: 'italic', textAlign: 'center' },
  scoreItem: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  scoreItemText: { fontSize: 16, color: '#2E7D32', fontWeight: '500' },
  scoreItemDate: { fontSize: 14, color: '#666' },
});

export default styless;
